def board_system3():
    print()
    print('                     This 3s grid is being initialized from index 1 to 9 .')
    print("          If you want to choose a particular position you've to enter index as shown below.")
    print()
    print()
    print('                                 |          |         ')
    print('                              1  |     2    |   3     ')
    print('                           -------------------------  ')
    print('                                 |          |         ')
    print('                             4   |     5    |   6     ')
    print('                           -------------------------  ')
    print('                                 |          |         ')
    print('                             7   |     8    |   9     ')


def board_system5():
    print()
    print('                     This 5s grid is being initialized from index 1 to 25 .')
    print("          If you want to choose a particular position you've to enter index as shown below.")
    print()
    print()
    print('                                 |          |          |          |       ')
    print('                              1  |     2    |    3     |     4    |    5  ')
    print('                          ------------------------------------------------')
    print('                                 |          |          |          |       ')
    print('                              6  |     7    |    8     |     9    |   10  ')
    print('                          ------------------------------------------------')
    print('                                 |          |          |          |       ')
    print('                             11  |    12    |    13    |    14    |   15  ')
    print('                          ------------------------------------------------')
    print('                                 |          |          |          |       ')
    print('                             16  |    17    |    18    |    19    |   20  ')
    print('                          ------------------------------------------------')
    print('                                 |          |          |          |       ')
    print('                             21  |    22    |    23    |    24    |   25  ')
import os
print(os.getcwd())